# Generated by Django 3.2.5 on 2021-12-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=150, null=True)),
                ('Clue', models.CharField(max_length=150, null=True)),
                ('Solution', models.CharField(max_length=150, null=True)),
                ('Answer', models.CharField(max_length=150, null=True)),
                ('CorrectAnswer', models.CharField(max_length=150, null=True)),
                ('ImageData', models.ImageField(default='images/default.jpg', upload_to='images')),
            ],
            options={
                'db_table': 'form_data',
            },
        ),
    ]
